#dnf install golang -y
#cp dispatch.service /etc/systemd/system/dispatch.service
#useradd roboshop
#rm -rf /app
#mkdir /app
#curl -L -o /tmp/dispatch.zip https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
#cd /app
#unzip /tmp/dispatch.zip
#cd /app
#go mod init dispatch
#go get
#go build
#systemctl daemon-reload
#systemctl enable dispatch
#systemctl start dispatch

- name: Install golang
  ansible.builtin.dnf:
    name: golang
    state: latest

#- name: Copy dispatch repo file
#  ansible.builtin.copy:
#    src: dispatch.service
#    dest: /etc/systemd/system/dispatch.service

- name: Run app Pre-setup
  ansible.builtin.include_role:
    name: common
    tasks_from: app_pre_setup.yml

- name: go lang commands
  ansible.builtin.shell: cd /app ; go mod init dispatch ; go get ; go build

- name: Run systemd_setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup